id: P9B9EBD27
initial_creation_type: ocr
source_metadata:
  volumes:
    2206f18410be4f189053ae7563a5b14a:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་འཇིག་རྟེན་དབང་ཕྱུག་ཡི་གེ་དྲུག་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
